In [1]:
import torch

In [2]:
# 2차원 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]]))

tensor([[1, 2],
        [3, 4]])


In [3]:
# GPU에 텐서 생성; 만약 GPU가 엔비디아 꺼가 아니면 안됨
print(torch.tensor([[1,2],[3,4]], device="cuda:0"))

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [4]:
# 데이터의 형태를 지정해주는 방식
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [6]:
temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(temp) # 그냥 GPU 텐서

temp1 = temp.to("cpu")
print(temp1) # CPU로 변경

temp2 = temp.to("cpu").numpy()
print(temp2) #ndarray로 변경

tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [7]:
# FloatTensor, DoubleTensor, LongTensor 등으로 데이터타입을 바로 설정해주면서 시작할 수도 있음.
temp = torch.DoubleTensor([[1,2],[3,4]])
print(temp)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [8]:
# 텐서 간 타입과 크기가 같으면 연산이 가능함.
v = torch.tensor([9,10])
w = torch.tensor([10,11])
print(v+w)

tensor([19, 21])


In [9]:
# 텐서의 차원을 변경하는 법: view를 사용함.
temp = torch.tensor([[1,2],[3,4]])
print(temp.view([4,1]))

# -1을 사용하면 알아서 지정해 줌.
print(temp.view(-1))

tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
